version: 2
jobs:
  install-packages:
    docker:
      - image: circleci/node:11.0.0    
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: echo "Installing files"
      - run: npm i
      - save_cache:
          key: node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  tests:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - attach_workspace:
          at: .
      - run: echo "running tests"
      - run: npm test -- --ci --coverage --detectOpenHandles --forceExit
      - run: curl https://codecov.io/bash -o codecov.sh
      - run: bash codecov.sh -t "$CODECOV_TOKEN"
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - attach_workspace:
          at: .
      - run: echo "building files"
      - run: npx ionic build
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - build
            - firebase.json
            - '.firebaserc'
  deploy:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run:
          name: deploy to firebase
          command: npx firebase-tools deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-packages
      - tests:
          requires:
            - install-packages
      - build:
          requires:
            - install-packages
      - deploy:
          requires:
            - build
            - tests
          filters:
            branches:
              only:
                - master
